name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclencher l'action lorsque tu pousses sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build et push de l'image Docker
        run: |
          docker build -t camille363/myportfolio:latest .
          docker push camille363/myportfolio:latest
